name: Terraform plan & apply

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    uses: vitor-avanco/fastfood-infra-k8s/.github/workflows/aws-terraform.yml@main
    with:
      aws-region: us-east-1
      terraform-directory-path: src
      terraform-version: 1.6.3
    secrets: inherit
    
