name: Terraform plan & apply

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    uses: ./.github/workflows/aws-terraform.yml
    with:
      aws-region: us-east-1
      terraform-directory-path: src
      terraform-version: 1.6.3
    secrets: inherit
